Fix versioning, bug fixing, new commands!

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -1,3 +1,17 @@
 #!/bin/bash
 
-pwsh "installer.ps1" "$@"
+if ! command -v pwsh >/dev/null 2>&1 ; then
+    echo "PowerShell is required!"
+
+    exit 1
+fi
+
+module="$HOME/.dotman/installer.ps1"
+
+if [[ -f "$module" ]]; then
+    pwsh "$module" "$@"
+else
+    echo "Installer is missing!"
+
+    exit 1
+fi
diff --git a/list b/list
--- a/list
+++ b/list
@@ -1,3 +1,17 @@
 #!/bin/bash
 
-pwsh "$HOME/.dotman/list.ps1" "$@"
+if ! command -v pwsh >/dev/null 2>&1 ; then
+    echo "PowerShell is required!"
+
+    exit 1
+fi
+
+module="$HOME/.dotman/list.ps1"
+
+if [[ -f "$module" ]]; then
+    pwsh "$module" "$@"
+else
+    echo "Module is missing!"
+
+    exit 1
+fi
